BEGIN;

ALTER TABLE outbox_jobs
  ADD COLUMN IF NOT EXISTS correlation_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS trace_parent TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS trace_state TEXT NOT NULL DEFAULT '';

COMMIT;
