FROM golang:1.25-alpine AS builder

RUN go install go.k6.io/xk6/cmd/xk6@v1.4.7
RUN xk6 build v1.2.1 \
    --with github.com/phymbert/xk6-sse@v0.1.12 \
    --output /k6

FROM alpine:3.22
COPY --from=builder /k6 /usr/bin/k6
ENTRYPOINT ["k6"]
